# Generated by Django 5.0.3 on 2024-03-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_bio_appuser_city_appuser_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='job_title',
            new_name='jobtitle',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
