# Generated by Django 5.0.3 on 2024-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='program',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
