# Generated by Django 5.0.3 on 2024-03-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='reciever',
        ),
    ]
