# Generated by Django 5.0.3 on 2024-03-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_rename_receiver_chatmessage_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
